---
title: Hashtag.Ai
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 5
language: en-uk
name: Hashtag AI
description: 'Artificial Intelligence: The next industrial revolution.'
author: Wilson Tjandra
nickname: wilson
bio: futurist
location: Singapore
url: http://hashtag.ai/
image: assets/images/casper.png
short_url: hashtag.ai
google_analytics: UA-69281367-1
disqus: username
baseurl: "/"
permalink: "/:title"
gems:
- jekyll-paginate
exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- ".travis.yml"
safe: false
lsi: false
username: wilson0205
repo: hashtag.ai
branch: master
relative_source: "../hashtag.ai/"
destination: "../"
production_url: https://hashtag.ai/
source_url: https://github.com/wilson0205/hashtag.ai/
